export const LISTAR_POKEMONS = 'LISTAR_POKEMONS';
export const SET_ERROR_POKEMONS = 'SET_ERROR_POKEMONS';
export const SET_LOADING_POKEMONS = 'SET_LOADING_POKEMONS';

export const LISTAR_TIPOS = 'LISTAR_TIPOS';
