export const LISTAR_POKEMONS = 'LISTAR_POKEMONS';
export const SET_ERROR_POKEMONS = 'SET_ERROR_POKEMONS';
export const SET_LOADING_POKEMONS = 'SET_LOADING_POKEMONS';
export const SET_FILTRADO_POKEMONS = 'SET_FILTRADO_POKEMONS';
export const ADD_TIPO_FILTRADO_POKEMONS = 'ADD_TIPO_FILTRADO_POKEMONS';
export const DEL_TIPO_FILTRADO_POKEMONS = 'DEL_TIPO_FILTRADO_POKEMONS';
export const UNICA_TIPO_FILTRADO_POKEMONS = 'UNICA_TIPO_FILTRADO_POKEMONS';
export const SET_PAGINA_POKEMONS = 'SET_PAGINA_POKEMONS';

export const LISTAR_TIPOS = 'LISTAR_TIPOS';
export const SET_ERROR_TIPOS = 'SET_ERROR_TIPOS';
export const SET_LOADING_TIPOS = 'SET_LOADING_TIPOS';